#!/usr/bin/env bash

set -e

CONFIG="utils/install.conf.yaml"
DOTBOT_DIR="utils/dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$HOME/.dotfiles"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
